// Generated by CoffeeScript 1.10.0
var addfolder;

addfolder = (function() {
  function addfolder($btn) {
    this.$btn = $btn;
    this.setOptions();
    this.bindEvents();
    console.log('ebb');
  }

  addfolder.prototype.setOptions = function() {
    return this.$btn = this.$btn;
  };

  addfolder.prototype.sendpath = function() {
    this.$path = ($('.selected_folder').data('path')) + $('#newfoldername').val();
    console.log('sendpath' + $('#newfoldername').val() + '??');
    if (!$('#newfoldername').val()) {
      return alert('faut donner un nom à ton dossier');
    } else {
      $('.cover').addClass('visible');
      console.log('sendpath' + this.$path);
      return $.ajax({
        type: 'POST',
        url: 'php/addfolder.php',
        data: {
          'path': this.$path
        }
      }).done(function(data) {
        var infophp;
        console.log('done' + data);
        infophp = JSON.parse(data);
        if (infophp[0] === 'ok') {
          return location.reload(true);
        }
      });
    }
  };

  addfolder.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(e) {
        console.log('click');
        return _this.sendpath();
      };
    })(this));
  };

  return addfolder;

})();

module.addfolder = addfolder;
