// Generated by CoffeeScript 1.10.0
var addslides;

addslides = (function() {
  function addslides($container, insertWithSrc) {
    this.$container = $container;
    this.insertWithSrc = insertWithSrc;
    this.getContext();
    console.log(this.insertWithSrc + '  @insertWithSrc');
    if (!this.insertWithSrc) {
      this.bindEvents();
    }
  }

  addslides.prototype.getContext = function($el) {
    this.$el = $el;
    this.$btn = this.$container.find('.addslide');
    this.$content = this.$container.find('.content');
    return this.$slides = this.$content.find('.slides');
  };

  addslides.prototype.returnid = function() {
    var d;
    d = new Date;
    this.$id = d.getTime();
    return this.$id;
  };

  addslides.prototype.addslide = function() {
    var showserver, txt;
    console.log('addslide = @imgsrc : ' + this.insertWithSrc);
    this.$newslide = $('#samples #slide').clone();
    if (this.insertWithSrc) {
      this.$newslide.find('img').attr('src', this.insertWithSrc);
    }
    this.$id = 'slide' + this.returnid();
    this.$newslide.attr('id', this.$id);
    this.$slides.append(this.$newslide);
    txt = new module.txteditor('#' + this.$id + ' .flex-caption');
    showserver = new module.showcloud($('#' + this.$id + ' img'));
    return $('body').addClass('savable');
  };

  addslides.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(event) {
        console.log('click');
        return _this.addslide();
      };
    })(this));
  };

  return addslides;

})();

module.addslides = addslides;
