// Generated by CoffeeScript 1.10.0
var closecloud;

closecloud = (function() {
  function closecloud($btn) {
    this.$btn = $btn;
    this.setOptions();
    this.bindEvents();
  }

  closecloud.prototype.setOptions = function() {
    this.$btn = this.$btn;
    return this.$cloudfinder = $('.server');
  };

  closecloud.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(e) {
        console.log('click');
        _this.$cloudfinder.addClass('hidden');
        $('body').removeClass('popin');
        $('.server').removeClass('addpageform');
        return $('.target').removeClass('target');
      };
    })(this));
  };

  return closecloud;

})();

module.closecloud = closecloud;
