// Generated by CoffeeScript 1.10.0
var cloud;

cloud = (function() {
  function cloud($cloud) {
    this.$cloud = $cloud;
    this.setOptions();
    this.bindEvents();
  }

  cloud.prototype.setOptions = function() {
    this.$renameinput = $('#renameinput');
    this.$folder = this.$cloud.find('.folder-trigger');
    this.$imgli = this.$cloud.find('li');
    this.$listimg = this.$cloud.find('.listimg');
    return this.$timer = void 0;
  };

  cloud.prototype.checkmovment = function() {
    var _that, newcloud;
    newcloud = this.$cloud.html();
    $('.cover').addClass('visible');
    _that = this;
    return $(newcloud).find('.listimg').each(function() {
      var idlist;
      idlist = $(this).attr('id');
      return $(this).find(' > li').each(function() {
        var newpath, oldpath;
        if (idlist !== $(this).data('from-where')) {
          console.log(idlist + ' -- ' + $(this).data('from-where') + ' -- ' + $(this).data('name'));
          oldpath = $('#' + $(this).data('from-where')).data('path') + $(this).data('name');
          newpath = $('#' + idlist).data('path') + $(this).data('name');
          _that.updateorder(oldpath, newpath);
        }
      });
    });
  };

  cloud.prototype.updateorder = function($oldpath, $newpath) {
    this.$oldpath = $oldpath;
    this.$newpath = $newpath;
    console.log(this.$oldpath + ' @$oldpath, ' + this.$newpath + '+@$newpath');
    return $.ajax({
      type: 'POST',
      url: 'php/move.php',
      data: {
        'newname': this.$newpath,
        'oldname': this.$oldpath
      }
    }).done(function(data) {
      $('.cover').removeClass('visible');
      return console.log('done' + data);
    });
  };

  cloud.prototype.checkmovmentdebounce = function() {
    var _that;
    clearTimeout(this.$timer);
    _that = this;
    this.$timer = setTimeout((function() {
      return _that.checkmovment();
    }), 1000);
  };

  cloud.prototype.bindEvents = function() {
    var _that;
    _that = this;
    this.$listimg.sortable({
      items: ':not(.notsortable)',
      connectWith: '.listimg'
    }).bind('sortupdate', function(e) {
      console.log('sortupdate');
      return _that.checkmovmentdebounce();
    });
    $('.folder:first-child').addClass('selected_folder');
    _that = this;
    this.$imgli.on('click', function(event) {
      $('.selected_folder').removeClass('selected_folder');
      $(this).addClass('selected_folder');
      $('.showurl').text(window.location.origin + '/' + $('.selected_folder').data('path-file'));
      $('.previewfile').empty();
      $('#cloud').removeClass('withpreview');
      console.log($(this).data('type'));
      if ($(this).data('type') === 'img') {
        $('.previewfile').append('<img src="' + $(this).data('path-file') + '" />');
        $('#cloud').addClass('withpreview');
      }
      if ($(this).data('type') === 'mp3') {
        $('.previewfile').append('<audio controls><source src="' + $(this).data('path-file') + '" type="audio/mpeg"></audio>');
        $('#cloud').addClass('withpreview');
      }
      if ($(this).data('type') === 'video') {
        $('.previewfile').append('<video width="300" controls><source src="' + $(this).data('path-file') + '" type="video/mp4"></video>');
        return $('#cloud').addClass('withpreview');
      }
    });
    return this.$folder.on('change', function(event) {
      console.log('licic');
      $('.selected_folder').removeClass('selected_folder');
      $(this).parent().addClass('selected_folder');
      return $('.showurl').text(window.location.origin + '/' + $('.selected_folder').data('path'));
    });
  };

  return cloud;

})();

module.cloud = cloud;
