// Generated by CoffeeScript 1.10.0
var savenav;

savenav = (function() {
  function savenav($btn, $txtedit) {
    this.$btn = $btn;
    this.$txtedit = $txtedit;
    this.setOptions();
    this.bindEvents();
  }

  savenav.prototype.setOptions = function() {
    this.$btn = this.$btn;
    this.$navjson = {};
    return this.$fileurl = $('body').data('navjson');
  };

  savenav.prototype.croalContent = function($container, $where) {
    var $tab;
    $tab = {};
    $container.find('.nav-group li').each((function(_this) {
      return function(index, element) {
        var $content_to_save, $el_content, $te;
        $te = _this.$txtedit;
        $el_content = $(element).find('.content:first-child');
        $content_to_save = $te.getCont($el_content.find('.editable').attr('id'));
        $tab[$el_id] = {
          'position': $where,
          'link': 'wie-wer-was',
          'linkopposite': 'qui-que-quoi',
          'title': 'Wie wer was',
          'datajson': 'p2',
          'speciallayout': '',
          'illustration': ''
        };
        return console.log($content_to_save + '  content_to_save ');
      };
    })(this));
    return $tab;
  };

  savenav.prototype.makeJson = function() {
    this.$navjson = this.croalContent($('.blocks.navigation'), 'header');
    return console.log(JSON.stringify(this.$navjson));
  };

  savenav.prototype.sendJson = function() {
    console.log('sendJson');
    $('body').removeClass('savable');
    return $.ajax({
      type: 'POST',
      url: 'php/changedata.php',
      data: {
        'fileurl': this.$fileurl,
        'content': JSON.stringify(this.$navjson)
      }
    }).done(function() {
      return location.reload(true);
    });
  };

  savenav.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(e) {
        return _this.makeJson();
      };
    })(this));
  };

  return savenav;

})();

module.savenav = savenav;
