// Generated by CoffeeScript 1.10.0
var newpagename;

newpagename = (function() {
  function newpagename($textfield) {
    this.$textfield = $textfield;
    this.bindEvents();
  }

  newpagename.prototype.onchangetitle = function() {
    var $makecleanurl, $newurl;
    $makecleanurl = new module.cleanurl(this.$textfield.val());
    $newurl = $makecleanurl.cleanstring(this.$textfield.val());
    console.log($newurl);
    return $('body').data('pagejson', $newurl);
  };

  newpagename.prototype.bindEvents = function() {
    return this.$textfield.change(function() {
      console.log('click');
      return this.onchangetitle();
    });
  };

  return newpagename;

})();

module.newpagename = newpagename;
