// Generated by CoffeeScript 1.10.0
var removeperso;

removeperso = (function() {
  function removeperso($btn) {
    this.$btn = $btn;
    this.bindEvents();
  }

  removeperso.prototype.getContext = function($el) {
    this.$el = $el;
    return this.$thisblock = this.$el.parent();
  };

  removeperso.prototype.removeBlock = function() {
    new module.sorting().suspend();
    this.$thisblock.remove();
    $('body').addClass('savable');
    return new module.sorting().reactive();
  };

  removeperso.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(event) {
        _this.getContext($(event.currentTarget));
        return _this.removeBlock();
      };
    })(this));
  };

  return removeperso;

})();

module.removeperso = removeperso;
