// Generated by CoffeeScript 1.10.0
var removeblocks;

removeblocks = (function() {
  function removeblocks($btn) {
    this.$btn = $btn;
    this.bindEvents();
  }

  removeblocks.prototype.getContext = function($el) {
    this.$el = $el;
    this.$thisblockid = this.$el.data('id-to-remove');
    this.$data_level = this.$el.data('level');
    this.$need_update_col_size = this.$el.data('need-update-col-size');
    return this.$grid = $('#' + this.$thisblockid).parent();
  };

  removeblocks.prototype.removeBlock = function() {
    new module.sorting().suspend();
    $('#' + this.$thisblockid).remove();
    if (this.$need_update_col_size) {
      new module.updatecolsize(this.$grid, this.$data_level);
    }
    new module.sorting().reactive();
    return $('body').addClass('savable');
  };

  removeblocks.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(event) {
        console.log('click');
        _this.getContext($(event.currentTarget));
        return _this.removeBlock();
      };
    })(this));
  };

  return removeblocks;

})();

module.removeblocks = removeblocks;
