// Generated by CoffeeScript 1.10.0
var removefile;

removefile = (function() {
  function removefile($btn) {
    this.$btn = $btn;
    this.bindEvents();
    console.log('removefile');
  }

  removefile.prototype.sendpath = function() {
    var impossible, name, path, type, warning;
    impossible = $('.selected_folder').data('deleatimpossible');
    if (impossible) {
      return false;
    }
    type = $('.selected_folder').hasClass('folder') ? 'folder' : 'file';
    name = $('.selected_folder').data('name');
    path = $('.selected_folder').data('path');
    warning = type === 'folder' ? 'Voulez-vous supprimer le dossier ' + name : 'Voulez-vous supprimer ' + name;
    if (type === 'file') {
      path += name;
    } else {
      warning += ', et tout ce qu\'il contient ';
    }
    warning += ' ?';
    console.log('path ' + path);
    console.log(' sendpath ' + type);
    if (confirm(warning)) {
      $.ajax({
        type: 'POST',
        url: 'php/remove.php',
        data: {
          'type': type,
          'path': path
        }
      }).done(function(data) {
        console.log('done' + data);
        return $('.selected_folder').remove();
      });
    }
    return false;
  };

  removefile.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(e) {
        console.log('click');
        return _this.sendpath();
      };
    })(this));
  };

  return removefile;

})();

module.removefile = removefile;
