// Generated by CoffeeScript 1.10.0
var replacefile;

replacefile = (function() {
  function replacefile($replaceimg) {
    this.$replaceimg = $replaceimg;
    this.setOptions();
    this.bindEvents();
  }

  replacefile.prototype.setOptions = function() {
    return this.$btn = this.$replaceimg.find('#insertimg');
  };

  replacefile.prototype.getContext = function($el) {
    var $targetblockimg, isfoder, isimg;
    this.$el = $el;
    this.$selected = this.$replaceimg.find('.selected_folder');
    isfoder = !(isimg = this.$selected.is('li'));
    if (isimg) {
      this.$newsrc = this.$selected.data('path-file');
      this.changeSrc(this.$newsrc);
    }
    if (isfoder) {
      $targetblockimg = $('.target').parents('.blocks.img');
      this.$newsrc = this.$selected.find('li:first-child').data('path-file');
      this.changeSrc(this.$newsrc);
      return this.$selected.find('> ul > li').not(':first-child').each(function(index) {
        this.$newsrc = $(this).data('path-file');
        console.log(index + '  ???' + this.$newsrc);
        return new module.addslides($targetblockimg, this.$newsrc).addslide();
      });
    }
  };

  replacefile.prototype.changeSrc = function($newsrc) {
    this.$newsrc = $newsrc;
    $('.target').attr('src', this.$newsrc);
    $('.target').removeClass('target');
    $('.server').addClass('hidden');
    $('body').removeClass('popin');
    return $('body').addClass('savable');
  };

  replacefile.prototype.bindEvents = function() {
    return this.$btn.on('click', (function(_this) {
      return function(event) {
        console.log('click replaceimg');
        return _this.getContext($(event.currentTarget));
      };
    })(this));
  };

  return replacefile;

})();

module.replacefile = replacefile;
