// Generated by CoffeeScript 1.10.0
var showcloud;

showcloud = (function() {
  function showcloud($btn) {
    this.$btn = $btn;
    this.setOptions();
    this.bindEvents();
  }

  showcloud.prototype.setOptions = function() {
    return this.$btn = this.$btn;
  };

  showcloud.prototype.bindEvents = function() {
    return this.$btn.on('click', function(event) {
      console.log('click showcloud');
      $(event.currentTarget).addClass('target');
      $('.server').removeClass('hidden');
      $('body').addClass('popin');
      console.log('yodfsdfsdf ');
      return $('.server img').each(function() {
        return $(this).attr('src', $(this).data('src'));
      });
    });
  };

  return showcloud;

})();

module.showcloud = showcloud;
