// Generated by CoffeeScript 1.10.0
var sorting;

sorting = (function() {
  function sorting($btn) {
    this.$btn = $btn;
    this.$sort = null;
    if (this.$btn) {
      this.bindEvents();
    }
  }

  sorting.prototype.suspend = function() {
    if (($('.active_sortable').lenght)) {
      return $('.active_sortable').sortable('destroy');
    }
  };

  sorting.prototype.reactive = function() {
    if (($('.active_sortable').lenght)) {
      return $('.active_sortable').sortable({
        handle: '.handlesort'
      }).bind('sortupdate', function() {
        $('body').addClass('savable');
      });
    }
  };

  sorting.prototype.bindEvents = function() {
    return this.$btn.on('click', function() {
      if (this.$sort === $(this).parent().parent()) {
        return;
      }
      if (this.$sort) {
        this.$sort.sortable('destroy');
      }
      this.$sort = $(this).parent().parent();
      $('.active_sortable').removeClass('active_sortable');
      this.$sort.addClass('active_sortable');
      this.$sort.sortable({
        handle: '.handlesort'
      }).bind('sortupdate', function() {
        $('body').addClass('savable');
      });
    });
  };

  return sorting;

})();

module.sorting = sorting;
