// Generated by CoffeeScript 1.10.0
var popin;

popin = (function() {
  function popin($btn) {
    this.$btn = $btn;
    this.checkbox = $('#showfilterlabel');
    this.bindEvents();
  }

  popin.prototype.bindEvents = function() {
    $('.mypopin .shield').on('click', (function(_this) {
      return function(e) {
        return $('body').removeClass('popin_opended');
      };
    })(this));
    return this.$btn.on('click', (function(_this) {
      return function(e) {
        var $url;
        $url = $(e.target).attr('href');
        console.log($url);
        $.ajax({
          url: $url,
          success: function(response) {
            console.log('damened N?? = ' + $(response).html());
            console.log($('#main', response).html());
            console.log($(response).filter('#main').html());
            $('body').addClass('popin_opended');
            $('.mypopin .content').html($(response).filter('#main'));
            $('.mypopin .content').append($(response).filter('script'));
          }
        });
        console.log('click : ' + $url);
        return false;
      };
    })(this));
  };

  return popin;

})();

module.popin = popin;
