// Generated by CoffeeScript 1.10.0
var searchfocus;

searchfocus = (function() {
  function searchfocus($btn, $field1) {
    this.$btn = $btn;
    this.$field = $field1;
    this.bindEvents();
  }

  searchfocus.prototype.bindEvents = function() {
    var $field;
    $field = this.$field;
    this.$field.focus();
    return this.$btn.change(function() {
      $field.focus();
    });
  };

  return searchfocus;

})();

module.searchfocus = searchfocus;
