// Generated by CoffeeScript 1.10.0
var filter;

filter = (function() {
  function filter($container) {
    this.$container = $container;
    this.select = this.$container.find('select');
    this.bindEvents();
  }

  filter.prototype.bindEvents = function() {
    return this.select.change((function(_this) {
      return function(e) {
        var $string;
        console.log('changed');
        $string = '?';
        _this.select.each(function(index) {
          if ($(this).find('option:selected').val() !== 'label') {
            $string += $(this).attr('id');
            $string += '=' + $(this).find('option:selected').val();
            $string += '&';
            console.log(index + ': ' + $(this).find('option:selected').text());
          }
        });
        return $('#main').load($string + ' #main');
      };
    })(this));
  };

  return filter;

})();

module.filter = filter;
