// Generated by CoffeeScript 1.10.0
var addperson, addslide, init, login, navigation, unlogin;

init = function() {
  var addblocks, addfolder, closecloud, cloud, cloudimages, deleatperso, deleatslide, removeblocks, removefile, replaceimg, replacemusic, savepage, showcloud, sorting, txtedit, uploadmodule;
  console.log('doc ready');
  addblocks = new module.addblocks($('.addblocks'), $('#samples'));
  removeblocks = new module.removeblocks($('.bin'));
  deleatperso = new module.removeperso($('.deleatperso'));
  deleatslide = new module.removeperso($('.deleatslide'));
  showcloud = new module.showcloud($('#main .img .flexslider .slides img, #main .perso img, #main .music .showcloud'));
  closecloud = new module.closecloud($('.shield'));
  replaceimg = new module.replacefile($('.replaceimg'));
  replacemusic = new module.replacefile($('.replacemusic'));
  cloud = new module.cloud($('#cloud'));
  cloudimages = new module.cloud($('#cloudimage'));
  addfolder = new module.addfolder($('.btnaddfolder'));
  removefile = new module.removefile($('.btndelatefolder'));
  sorting = new module.sorting($('.handlesort'));
  uploadmodule = new module.up($('.uploadmodule'));
  txtedit = new module.txteditor('#main .editable');
  savepage = new module.savepage($('#main'), $('#savepage'), txtedit);
  $('#main .blocks .listbtnright').each(function() {
    var updateclassoption;
    updateclassoption = new module.updateclassoption($(this));
  });
  $('input[type=checkbox]').change(function() {
    $('body').addClass('savable');
  });
  return $('.btn').on('click', function() {
    $('body').addClass('savable');
  });
};

$(document).ready(init);

navigation = new module.navigation($('.navigation'));

login = new module.login($('.popinlogin form'));

unlogin = new module.unlogin($('#unlog'));

addslide = new module.addslides($('#main .img'));

addperson = new module.addpersons($('#main .perso'));

if (!$('body').hasClass('managefile')) {
  window.onbeforeunload = function() {
    if (!$('body').hasClass('savable')) {
      return void 0;
    }
    return "t'a oublié d'enregistrer, c'est normal ? ";
  };
}
