// Generated by CoffeeScript 1.10.0
var addperson, addslide, init, login, navigation, savepage, txtedit, unlogin;

init = function() {
  var addblocks, addfolder, closecloud, cloud, deleatperso, deleatslide, removeblocks, removefile, replaceimg, showcloud, sorting;
  console.log('doc ready');
  addblocks = new module.addblocks($('.addblocks'), $('#samples'));
  removeblocks = new module.removeblocks($('.bin'));
  deleatperso = new module.removeperso($('.deleatperso'));
  deleatslide = new module.removeperso($('.deleatslide'));
  showcloud = new module.showcloud($('#main .img .flexslider .slides img, #main .perso img'));
  closecloud = new module.closecloud($('.shield'));
  replaceimg = new module.replaceimg($('.replaceimg ul li'));
  cloud = new module.cloud($('#cloud'));
  addfolder = new module.addfolder($('.btnaddfolder'));
  removefile = new module.removefile($('.btndelatefolder'));
  $('#main .blocks .listbtnright').each(function() {
    var updateclassoption;
    updateclassoption = new module.updateclassoption($(this));
  });
  $('input[type=checkbox]').change(function() {
    $('body').addClass('savable');
  });
  $('.btn').on('click', function() {
    $('body').addClass('savable');
  });
  return sorting = new module.sorting($('.handlesort'));
};

$(document).ready(init);

txtedit = new module.txteditor('#main .editable');

navigation = new module.navigation($('.navigation'));

login = new module.login($('.popinlogin form'));

unlogin = new module.unlogin($('#unlog'));

savepage = new module.savepage($('#main'), $('#savepage'), txtedit);

addslide = new module.addslides($('#main .img'));

addperson = new module.addpersons($('#main .perso'));

if (!$('body').hasClass('managefile')) {
  window.onbeforeunload = function() {
    if (!$('body').hasClass('savable')) {
      return void 0;
    }
    return "t'a oublié d'enregistrer, c'est normal ? ";
  };
}
