// Generated by CoffeeScript 1.10.0
var addperson, addslide, init, login, navigation, savepage, txtedit, unlogin;

init = function() {
  var addblocks, closecloud, deleatperso, removeblocks, replaceimg, showcloud;
  console.log('doc ready');
  addblocks = new module.addblocks($('.addblocks'), $('#samples'));
  removeblocks = new module.removeblocks($('.bin'));
  deleatperso = new module.removeperso($('.deleatperso'));
  showcloud = new module.showcloud($('#main .img .flexslider .slides img, #main .perso img'));
  closecloud = new module.closecloud($('.shield'));
  replaceimg = new module.replaceimg($('.server img'));
  $('#main .blocks .listbtnright').each(function() {
    var updateclassoption;
    updateclassoption = new module.updateclassoption($(this));
  });
  $('input[type=checkbox]').change(function() {
    $('body').addClass('savable');
  });
  $('.btn').on('click', function() {
    $('body').addClass('savable');
  });
  if ($('.persons').length > 1) {
    return $('.persons').sortable({
      handle: '.moveperso'
    }).bind('sortupdate', function() {
      $('body').addClass('savable');
    });
  } else {
    return $('#main').sortable({
      handle: '.handle'
    }).bind('sortupdate', function() {
      $('body').addClass('savable');
    });
  }
};

$(document).ready(init);

txtedit = new module.txteditor('#main .editable');

navigation = new module.navigation($('.navigation'));

login = new module.login($('.popinlogin form'));

unlogin = new module.unlogin($('#unlog'));

savepage = new module.savepage($('#main'), $('#savepage'), txtedit);

addslide = new module.addslides($('#main .img'));

addperson = new module.addpersons($('#main .perso'));

window.onbeforeunload = function() {
  if (!$('body').hasClass('savable')) {
    return void 0;
  }
  return "t'a oublié d'enregistrer, c'est normal ? ";
};
