// Generated by CoffeeScript 1.10.0
var debounce, init, navigation;

debounce = function(func, threshold, execAsap) {
  var debounced, timeout;
  timeout = false;
  return debounced = function() {
    var args, delayed, obj;
    obj = this;
    args = arguments;
    delayed = function() {
      if (!execAsap) {
        func.apply(obj, args);
      }
      return timeout = null;
    };
    if (timeout) {
      clearTimeout(timeout);
    } else if (execAsap) {
      func.apply(obj, args);
    }
    return timeout = setTimeout(delayed, threshold || 100);
  };
};

init = function() {
  var bierfilter, popinnewsletter, searchfocus;
  console.log('doc ready');
  if (($('.blocks.filter').length)) {
    bierfilter = new module.filter($('.blocks.filter'), debounce);
  }
  popinnewsletter = new module.popin($('.top_menu li:last-child a'));
  return searchfocus = new module.searchfocus($('#showsearch'), $('#s'));
};

$(window).load(init);

navigation = new module.navigation($('.navigation'));
