// Generated by CoffeeScript 1.10.0
var debounce, init, navigation;

debounce = function(func, threshold, execAsap) {
  var debounced, timeout;
  timeout = false;
  return debounced = function() {
    var args, delayed, obj;
    obj = this;
    args = arguments;
    delayed = function() {
      if (!execAsap) {
        func.apply(obj, args);
      }
      return timeout = null;
    };
    if (timeout) {
      clearTimeout(timeout);
    } else if (execAsap) {
      func.apply(obj, args);
    }
    return timeout = setTimeout(delayed, threshold || 100);
  };
};

init = function() {
  var cart, inview, newsletter, popin, produit, sticky;
  console.log('doc ready');
  $('body').addClass('doc-ready');
  if (($('.addtocart').length)) {
    produit = new module.produit($('.addtocart'));
  }
  if (($('.flexslider').length)) {
    $('.flexslider').flexslider({
      animation: 'slide',
      start: function(slider) {
        $('body').addClass('slider-ready');
      }
    });
  }
  if (($('.cartpage').length)) {
    cart = new module.cart($('.cartpage'));
  }
  if (($('.btnpopin').length)) {
    console.log('ya popin');
    popin = new module.popin($('.btnpopin'));
  }
  if (($('#contact-form').length)) {
    newsletter = new module.newsletter($('#contact-form'));
  }
  if (($('.sticky').length)) {
    sticky = new Waypoint.Sticky({
      element: $('.sticky')[0]
    });
    return inview = new Waypoint.Inview({
      element: $('#stop_stiky')[0],
      enter: function(direction) {
        $('.sticky').addClass('fixed-at-bottom');
        console.log('Enter triggered with direction ' + direction);
      },
      exited: function(direction) {
        if (direction === 'up') {
          $('.sticky').removeClass('fixed-at-bottom');
          console.log('remove : ' + direction);
        }
      }
    });
  }
};

$(window).load(init);

navigation = new module.navigation($('.navigation'));
