// Generated by CoffeeScript 1.10.0
var produit;

produit = (function() {
  function produit($btn) {
    var $cart;
    this.$btn = $btn;
    if (Cookies.get('cart')) {
      $cart = $.parseJSON(Cookies.get('cart'));
      $('.icon-cart').attr('data-nb-article', $cart.length);
    }
    this.bindEvents();
  }

  produit.prototype.isincart = function($id, $el) {
    var i, l, ret;
    l = $el.length;
    i = 0;
    ret = false;
    while (i < l) {
      console.log($el['id'] + '==' + $id);
      if ($el[0].id === $id) {
        $el[0].quantity += 1;
        ret = $el;
      }
      i++;
    }
    return ret;
  };

  produit.prototype.bindEvents = function() {
    var _isincart;
    _isincart = this.isincart;
    return this.$btn.on('click', function() {
      var $cart, $modified_cart, $newelement;
      $newelement = {
        id: $(this).data('id'),
        title: $(this).data('title'),
        cost: $(this).data('cost'),
        postal: $(this).data('postal'),
        quantity: 1,
        image: $(this).data('image'),
        descrition: $(this).data('descrition')
      };
      if (Cookies.get('cart')) {
        $cart = $.parseJSON(Cookies.get('cart'));
        $modified_cart = _isincart($(this).data('id'), $cart);
        if (!$modified_cart) {
          $cart.push($newelement);
        } else {
          $cart = $modified_cart;
        }
      } else {
        $cart = [$newelement];
      }
      Cookies.set('cart', $cart);
      $('.icon-cart').attr('data-nb-article', $cart.length);
    });
  };

  return produit;

})();

module.produit = produit;
